# Generated by Django 4.2 on 2025-01-15 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genre',
            new_name='Categ',
        ),
        migrations.RenameModel(
            old_name='Movie',
            new_name='Produs',
        ),
        migrations.AlterModelOptions(
            name='categ',
            options={'verbose_name_plural': 'Categorii de produse'},
        ),
        migrations.AlterModelOptions(
            name='produs',
            options={'verbose_name_plural': 'Produse'},
        ),
    ]
