# Generated by Django 4.2 on 2025-01-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_rename_genre_categ_rename_movie_produs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magazin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='produs',
            old_name='genre',
            new_name='Categ',
        ),
        migrations.RenameField(
            model_name='produs',
            old_name='title',
            new_name='Denumire',
        ),
        migrations.RenameField(
            model_name='produs',
            old_name='description',
            new_name='Descriere',
        ),
        migrations.RenameField(
            model_name='produs',
            old_name='rating',
            new_name='Garantie_luni',
        ),
        migrations.RenameField(
            model_name='produs',
            old_name='released',
            new_name='Lansat',
        ),
        migrations.RemoveField(
            model_name='produs',
            name='actors',
        ),
        migrations.DeleteModel(
            name='Actor',
        ),
        migrations.AddField(
            model_name='produs',
            name='Magazine',
            field=models.ManyToManyField(to='viewer.magazin'),
        ),
    ]
