# Generated by Django 4.2 on 2025-01-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_rename_categ_produs_categ_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magazin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magazin', models.CharField(max_length=128)),
                ('retea', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Magazine',
            },
        ),
    ]
