# Generated by Django 4.2 on 2025-01-23 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viewer', '0008_operatorprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cerere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cerere', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cereri', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SelectedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.produs')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.magazin')),
            ],
            options={
                'verbose_name_plural': 'Selected Data',
            },
        ),
        migrations.CreateModel(
            name='Preturi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pret', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cerere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preturi', to='viewer.cerere')),
                ('magazin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.magazin')),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.produs')),
            ],
        ),
    ]
