# Generated by Django 4.2 on 2025-01-23 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viewer', '0010_selecteddata_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_saved', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.produs')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.magazin')),
            ],
            options={
                'verbose_name_plural': 'Saved Prices',
            },
        ),
    ]
