# Generated by Django 4.2 on 2025-01-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0011_savedprices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedprices',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
