# Generated by Django 4.2 on 2025-01-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0012_alter_savedprices_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='selecteddata',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
